spring.application.name=c0924l1

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/cms
spring.datasource.username=root
spring.datasource.password=28101998
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
